services:
  app:
    image: ribbon/app
    ports:
      - 443:443/tcp
    volumes:
      - ./app:/app
    links:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - ./db:/var/lib/mysql
  dns:
    container_name: nadeco
    image: nadeco:latest
    build:
      context: ./nadeco
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nadeco/config.yaml:/config.yaml
    ports:
      - 53:53/udp
